# conf/config.yaml
defaults:
  - _self_
  - dataset: null
  - logging: simple

device: "cuda:0"

training:
  name: ""
  checkpoint_path: null
  batch_size: 1024
  num_workers: 8
  persistent_workers: True
  pin_memory: False
  epochs: 1000
  lr: 1e-4
  weight_decay: 1e-7
  gamma: 0.995
  grad_clip: null
  num_chunks: 1
  ridge: 1e-3

eval:
  t: null
  label_indices: []

scheduler:
  pretrained: null
  start: 0
  num_train_timesteps: 1000
  step: 1
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: linear

model:
  num_eigenfunctions: 256
  time_emb_dim: 256       
  base_channels: 64
  channel_mults: [1, 2, 4, 8]
  min_resolution: 8
  max_channels: 512
  num_res_blocks: 1
  append_last: False
  pooling: average
  dropout: 0.0

hydra:
  run:
    dir: ./runs/${dataset.name}/phi_${scheduler.num_train_timesteps}-${scheduler.step}_k${model.num_eigenfunctions}_chunks${training.num_chunks}_ridge${training.ridge}_epochs${training.epochs}_${training.name}
  job:
    chdir: true